// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package testclient

import (
	"net/http"

	"github.com/Yamashou/gqlgenc/client"
)

type TestClient interface {
}

type Client struct {
	Client *client.Client
}

func NewClient(cli *http.Client, baseURL string, options ...client.HTTPRequestOption) TestClient {
	return &Client{Client: client.NewClient(cli, baseURL, options...)}
}

type Query struct {
	VirtualMachine VirtualMachine "json:\"virtualMachine\" graphql:\"virtualMachine\""
	Entities       []Entity       "json:\"_entities\" graphql:\"_entities\""
	Service        Service        "json:\"_service\" graphql:\"_service\""
}
