package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/virtual-machine-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// VirtualMachine returns VirtualMachineResolver implementation.
func (r *Resolver) VirtualMachine() VirtualMachineResolver { return &virtualMachineResolver{r} }

type queryResolver struct{ *Resolver }
type virtualMachineResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) Node(ctx context.Context, id gidx.PrefixedID) (generated.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}
func (r *queryResolver) Nodes(ctx context.Context, ids []gidx.PrefixedID) ([]generated.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}
func (r *queryResolver) VirtualMachines(ctx context.Context, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.VirtualMachineOrder, where *generated.VirtualMachineWhereInput) (*generated.VirtualMachineConnection, error) {
	panic(fmt.Errorf("not implemented: VirtualMachines - virtualMachines"))
}
