package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// VirtualMachine returns VirtualMachineResolver implementation.
func (r *Resolver) VirtualMachine() VirtualMachineResolver { return &virtualMachineResolver{r} }

type queryResolver struct{ *Resolver }
type virtualMachineResolver struct{ *Resolver }
