package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"go.infratographer.com/virtual-machine-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindLocationByID is the resolver for the findLocationByID field.
func (r *entityResolver) FindLocationByID(ctx context.Context, id gidx.PrefixedID) (*Location, error) {
	panic(fmt.Errorf("not implemented: FindLocationByID - findLocationByID"))
}

// FindResourceOwnerByID is the resolver for the findResourceOwnerByID field.
func (r *entityResolver) FindResourceOwnerByID(ctx context.Context, id gidx.PrefixedID) (*ResourceOwner, error) {
	panic(fmt.Errorf("not implemented: FindResourceOwnerByID - findResourceOwnerByID"))
}

// FindVirtualMachineByID is the resolver for the findVirtualMachineByID field.
func (r *entityResolver) FindVirtualMachineByID(ctx context.Context, id gidx.PrefixedID) (*generated.VirtualMachine, error) {
	panic(fmt.Errorf("not implemented: FindVirtualMachineByID - findVirtualMachineByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
