package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"go.infratographer.com/example-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindVirtMByID is the resolver for the findVirtMByID field.
func (r *entityResolver) FindVirtMByID(ctx context.Context, id gidx.PrefixedID) (*generated.VirtM, error) {
	panic(fmt.Errorf("not implemented: FindVirtMByID - findVirtMByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
