package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"go.infratographer.com/virtual-machine-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindLocationByID is the resolver for the findLocationByID field.
func (r *entityResolver) FindLocationByID(ctx context.Context, id gidx.PrefixedID) (*Location, error) {
	return &Location{ID: id}, nil
}

// FindResourceOwnerByID is the resolver for the findResourceOwnerByID field.
func (r *entityResolver) FindResourceOwnerByID(ctx context.Context, id gidx.PrefixedID) (*ResourceOwner, error) {
	return &ResourceOwner{ID: id}, nil
}

// FindVirtualMachineByID is the resolver for the findVirtualMachineByID field.
func (r *entityResolver) FindVirtualMachineByID(ctx context.Context, id gidx.PrefixedID) (*generated.VirtualMachine, error) {
	return r.client.VirtualMachine.Get(ctx, id)
}

// FindVirtualMachineCPUConfigByID is the resolver for the findVirtualMachineCPUConfigByID field.
func (r *entityResolver) FindVirtualMachineCPUConfigByID(ctx context.Context, id gidx.PrefixedID) (*generated.VirtualMachineCPUConfig, error) {
	return r.client.VirtualMachineCPUConfig.Get(ctx, id)
}

// FindVirtualMachineMemoryConfigByID is the resolver for the findVirtualMachineMemoryConfigByID field.
func (r *entityResolver) FindVirtualMachineMemoryConfigByID(ctx context.Context, id gidx.PrefixedID) (*generated.VirtualMachineMemoryConfig, error) {
	return r.client.VirtualMachineMemoryConfig.Get(ctx, id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
