package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"go.infratographer.com/virtual-machine-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// VirtualMachineMemoryConfig is the resolver for the virtualMachineMemoryConfig field.
func (r *queryResolver) VirtualMachineMemoryConfig(ctx context.Context, id gidx.PrefixedID) (*generated.VirtualMachineMemoryConfig, error) {
	return r.client.VirtualMachineMemoryConfig.Get(ctx, id)
}
